In [1]:
import sys
import warnings
if not sys.warnoptions:
    warnings.simplefilter('ignore')

<pre>
Sequential model is the linear stack of layers.
Sequential model receives the data whenever we call fit function on the model

What format is accepatble for the input data?
fit function is defined as

fit (x=none, y=none, batch_size=none, epochs=1, verbose=1, callbacks=none, validation_split=0.0, validation_data=none, shuffle=true, class_weight=none, sample_weight=none, initial_epoch=0, steps_per_epoch=none, validation_steps=none, validation_batch_size=none, validation_freq=1, max_queue_size=10, workers=1, use_multiprocessing=True)

tensorflow.org/api_docs/python/tf/keras/Sequential#fit

x - input data, it should be in the form of numpy array or list of arrays(in case the model has multiple inputs)

y - output data, the format should be same as that of the input data
</pre>

# Data Preparation and Processing

In [3]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [4]:
train_samples=[]
train_labels=[]

<pre>
Data->

An experimental drug was tested on individuals from ages 13 to 100 in clinical trial
The trial had  2100 participants. Half were under the age of 65 and half were 65 years or older
95% of the patients above 65 years of age experienced side effects
95% of the patients below 65 years experienced no side effects
</pre>

In [6]:
for i in range(50):
    #5% young individuals who experience side effects
    random_younger=randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    #5% old individuals who did not experience side effects
    random_old=randint(65,100)
    train_samples.append(random_old)
    train_labels.append(0)
    
for i in range(1000):
    #95% young individuals who did not experience side effects
    random_younger=randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)
    
    #95% old individuals who experience side effects
    random_old=randint(65,100)
    train_samples.append(random_old)
    train_labels.append(1)    

In [7]:
for i in train_samples:
    print(i)

43
82
18
76
40
71
14
87
63
91
46
78
20
78
56
69
37
91
62
66
39
81
34
98
54
100
43
72
29
91
56
75
38
81
43
93
23
66
40
99
30
83
13
90
58
72
40
86
20
75
31
69
15
82
58
72
26
82
56
79
31
84
41
70
20
71
44
67
46
83
29
84
16
94
20
84
15
74
17
98
33
98
54
88
55
65
28
81
20
78
27
80
55
67
61
89
44
84
47
87
37
77
63
82
25
78
19
95
46
85
21
97
55
71
34
81
62
92
57
97
27
95
26
84
27
78
22
70
57
65
59
84
58
98
36
67
14
97
18
94
24
99
26
74
49
99
51
99
45
89
42
97
17
76
25
77
15
89
38
86
32
90
64
73
24
91
63
75
38
70
35
68
37
94
42
96
14
81
38
87
40
68
39
93
41
79
27
73
54
69
53
92
49
85
50
75
15
94
51
99
54
100
29
65
15
72
26
99
28
91
55
86
41
90
55
77
42
75
16
99
23
97
63
76
16
87
20
83
29
91
52
87
64
84
36
90
23
83
34
76
13
71
61
90
17
77
53
87
60
72
43
74
25
84
28
84
17
97
14
77
50
92
23
92
56
96
24
85
34
86
57
66
24
88
57
100
46
100
41
76
15
94
50
80
38
96
45
98
45
100
15
68
30
82
25
89
46
96
58
85
13
95
17
65
64
67
52
96
34
84
28
86
44
73
40
80
32
76
59
67
22
76
59
90
55
87
24
88
42
83
53
92

In [9]:
for i in train_labels:
    print(i)

1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1


In [10]:
# Converting into numpy array
train_samples=np.array(train_samples)
train_labels=np.array(train_labels)

In [11]:
train_samples

array([43, 82, 18, ..., 83, 30, 86])

In [12]:
train_labels

array([1, 0, 1, ..., 1, 0, 1])

In [16]:
# Shuffling the data to get rid of the order if imposed during the data generation
train_labels, train_samples =shuffle(train_labels,train_samples)

In [17]:
train_samples

array([59, 54, 53, ..., 75, 94, 56])

In [25]:
# Normalizing the data
#scaling down the sample, which currently is 13-64 to 0-1 range using minmaxscaler
scaler=MinMaxScaler(feature_range=(0,1))
#transforming the samples,reshape param is just a formality as fir_transform doesnot accept 1D 
#data by default
scaled_train_samples=scaler.fit_transform(train_samples.reshape(-1,1))

In [26]:
scaled_train_samples

array([[0.52873563],
       [0.47126437],
       [0.45977011],
       ...,
       [0.71264368],
       [0.93103448],
       [0.49425287]])

In [1]:
import sys
import warnings
if not sys.warnoptions:
    warnings.simplefilter('ignore')

# Building a artificial neural network

In [2]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy

Using TensorFlow backend.


In [3]:
model=Sequential([
    Dense(units=16, input_shape=(1,), activation='relu'),
    Dense(units=32, activation='relu'),
    Dense(units=2,activation='softmax'),
])

In [4]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_2 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


softmax activation function gives us the probabilities of the output classes